// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/product-faq/Current.tsx": () => import("../components/mockups/product-faq/Current.tsx"),
  "./components/mockups/product-faq/Enhanced.tsx": () => import("../components/mockups/product-faq/Enhanced.tsx")
};
