import { boolean, integer, pgTable, serial, text, timestamp } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

export const slidersTable = pgTable("sliders", {
  id: serial("id").primaryKey(),
  title: text("title").notNull(),
  subtitle: text("subtitle"),
  description: text("description"),
  imageUrl: text("image_url"),
  ctaPrimaryText: text("cta_primary_text"),
  ctaPrimaryHref: text("cta_primary_href"),
  ctaSecondaryText: text("cta_secondary_text"),
  ctaSecondaryHref: text("cta_secondary_href"),
  sortOrder: integer("sort_order").notNull().default(0),
  isActive: boolean("is_active").notNull().default(true),
  showCatalogButton: boolean("show_catalog_button").notNull().default(false),
  overlayEnabled: boolean("overlay_enabled").notNull().default(true),
  overlayColor: text("overlay_color").default("#021423"),
  overlayFromOpacity: integer("overlay_from_opacity").notNull().default(92),
  overlayToOpacity: integer("overlay_to_opacity").notNull().default(12),
  textColor: text("text_color").default("#ffffff"),
  ctaPrimaryBg: text("cta_primary_bg").default("#021423"),
  ctaSecondaryBg: text("cta_secondary_bg").default("rgba(255,255,255,0.06)"),
  // Locale-specific text fields (tr = default/base above)
  titleEn: text("title_en"),
  titleDe: text("title_de"),
  titleFr: text("title_fr"),
  titleIt: text("title_it"),
  titleAr: text("title_ar"),
  titleRu: text("title_ru"),
  titleFa: text("title_fa"),
  titleKa: text("title_ka"),
  titleBg: text("title_bg"),
  titleAz: text("title_az"),
  subtitleEn: text("subtitle_en"),
  subtitleDe: text("subtitle_de"),
  subtitleFr: text("subtitle_fr"),
  subtitleIt: text("subtitle_it"),
  subtitleAr: text("subtitle_ar"),
  subtitleRu: text("subtitle_ru"),
  subtitleFa: text("subtitle_fa"),
  subtitleKa: text("subtitle_ka"),
  subtitleBg: text("subtitle_bg"),
  subtitleAz: text("subtitle_az"),
  descriptionEn: text("description_en"),
  descriptionDe: text("description_de"),
  descriptionFr: text("description_fr"),
  descriptionIt: text("description_it"),
  descriptionAr: text("description_ar"),
  descriptionRu: text("description_ru"),
  descriptionFa: text("description_fa"),
  descriptionKa: text("description_ka"),
  descriptionBg: text("description_bg"),
  descriptionAz: text("description_az"),
  ctaPrimaryTextEn: text("cta_primary_text_en"),
  ctaPrimaryTextDe: text("cta_primary_text_de"),
  ctaPrimaryTextFr: text("cta_primary_text_fr"),
  ctaPrimaryTextIt: text("cta_primary_text_it"),
  ctaPrimaryTextAr: text("cta_primary_text_ar"),
  ctaPrimaryTextRu: text("cta_primary_text_ru"),
  ctaPrimaryTextFa: text("cta_primary_text_fa"),
  ctaPrimaryTextKa: text("cta_primary_text_ka"),
  ctaPrimaryTextBg: text("cta_primary_text_bg"),
  ctaPrimaryTextAz: text("cta_primary_text_az"),
  ctaSecondaryTextEn: text("cta_secondary_text_en"),
  ctaSecondaryTextDe: text("cta_secondary_text_de"),
  ctaSecondaryTextFr: text("cta_secondary_text_fr"),
  ctaSecondaryTextIt: text("cta_secondary_text_it"),
  ctaSecondaryTextAr: text("cta_secondary_text_ar"),
  ctaSecondaryTextRu: text("cta_secondary_text_ru"),
  ctaSecondaryTextFa: text("cta_secondary_text_fa"),
  ctaSecondaryTextKa: text("cta_secondary_text_ka"),
  ctaSecondaryTextBg: text("cta_secondary_text_bg"),
  ctaSecondaryTextAz: text("cta_secondary_text_az"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});

export const insertSliderSchema = createInsertSchema(slidersTable).omit({ id: true, createdAt: true, updatedAt: true });
export type InsertSlider = z.infer<typeof insertSliderSchema>;
export type Slider = typeof slidersTable.$inferSelect;
